// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// // import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
// // import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// ///
// ///
// ///
// ///
// ///
//
// await Firebase.initializeApp(
// options: DefaultFirebaseOptions.currentPlatform,
// );
//
//
//
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDT54N0ip5rYdUfqsfnA2AqejCsorFJX1Y',
//     appId: '1:1016369170311:web:f97f3acb68dadae50b7522',
//     messagingSenderId: '1016369170311',
//     projectId: 'swe6733-adventure-quest',
//     authDomain: 'swe6733-adventure-quest.firebaseapp.com',
//     storageBucket: 'swe6733-adventure-quest.appspot.com',
//     measurementId: 'G-F1HBBJ9HRG',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCLufUBJkMhZRkyDqDVKA2N3yywIi9XWQw',
//     appId: '1:1016369170311:android:18c8b1bc04c6e73f0b7522',
//     messagingSenderId: '1016369170311',
//     projectId: 'swe6733-adventure-quest',
//     storageBucket: 'swe6733-adventure-quest.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD5PCxet5ksdMVlZLT2zlcc33ytWeA8E8I',
//     appId: '1:1016369170311:ios:33457535c4edde6f0b7522',
//     messagingSenderId: '1016369170311',
//     projectId: 'swe6733-adventure-quest',
//     storageBucket: 'swe6733-adventure-quest.appspot.com',
//     iosClientId: '1016369170311-8jhfoodvhnj1arfv80qjv65d2kg3b3gd.apps.googleusercontent.com',
//     iosBundleId: 'com.example.myApp',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyD5PCxet5ksdMVlZLT2zlcc33ytWeA8E8I',
//     appId: '1:1016369170311:ios:33457535c4edde6f0b7522',
//     messagingSenderId: '1016369170311',
//     projectId: 'swe6733-adventure-quest',
//     storageBucket: 'swe6733-adventure-quest.appspot.com',
//     iosClientId: '1016369170311-8jhfoodvhnj1arfv80qjv65d2kg3b3gd.apps.googleusercontent.com',
//     iosBundleId: 'com.example.myApp',
//   );
// }
